openapi: 3.0.3
info:
  title: ReceiptManager API
  version: "0.1.0"
servers:
  - url: http://localhost:4010
paths:
  /receipts:
    post:
      summary: Create a receipt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReceiptRequest'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseEnvelope'
                  - type: object
                    properties:
                      payload:
                        $ref: '#/components/schemas/Receipt'
                      meta:
                        nullable: true
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEnvelope'
              examples:
                validation:
                  value:
                    request_id: "req-1"
                    timestamp: "2025-11-03T02:00:00Z"
                    code: "BAD_REQUEST"
                    message: "Validation failed"
                    payload: null
                    meta: null
                    errors:
                      - field: "amount"
                        reason: "必須為正數"
    get:
      summary: List receipts (paginated)
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseEnvelope'
                  - type: object
                    properties:
                      payload:
                        type: array
                        items:
                          $ref: '#/components/schemas/Receipt'
                      meta:
                        type: object
                        properties:
                          page:
                            type: integer
                          size:
                            type: integer
                          total:
                            type: integer
  /receipts/{id}:
    get:
      summary: Get single receipt
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseEnvelope'
                  - type: object
                    properties:
                      payload:
                        $ref: '#/components/schemas/Receipt'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEnvelope'
              examples:
                notfound:
                  value:
                    request_id: "req-404"
                    timestamp: "2025-11-03T02:00:00Z"
                    code: "NOT_FOUND"
                    message: "找不到該收據"
                    payload: null
                    meta: null
                    errors:
                      - field: "id"
                        reason: "不存在"
components:
  schemas:
    ResponseEnvelope:
      $ref: './components-response-envelope.yaml#/components/schemas/ResponseEnvelope'
    Receipt:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "午餐"
        amount:
          type: number
          format: float
          example: 120.5
        date:
          type: string
          format: date
          example: "2025-11-01"
      required:
        - id
        - title
        - amount
    CreateReceiptRequest:
      type: object
      properties:
        title:
          type: string
        amount:
          type: number
          format: float
        date:
          type: string
          format: date
      required:
        - title
        - amount